### ISSUE TITLE
Evaluate Impact of Preloading Fonts on Performance

### ISSUE THREAD

**Issue by samuelecalamita** [diva-e-aem/eds-boilerplate#22]
We need to investigate whether using the preload flag to load fonts has a positive impact on performance. Currently, our fonts are loaded without this optimization, and Franz suspect that preloading them might improve the page load times and overall user experience.

**Comment by eKrausedivae** [comment]
Normal load (not preloaded):
![Image](https://github.com/user-attachments/assets/6e5b4eb7-c748-44b5-a3a1-8ee5d4d914ca)

Preloaded in head:
![Image](https://github.com/user-attachments/assets/8cf116bd-e5af-4d8f-833b-a9e8569031f2)
![Image](https://github.com/user-attachments/assets/2d0eaa1d-ae53-42c8-8b13-f487627068f6)

**Comment by samuelecalamita** [comment]
@eKrausedivae What are your Thoughts? is there any benefits?

**Comment by eKrausedivae** [comment]
As you can see in the screenshots it was much slower preloaded than the current loading (I compared with local as well as on the live branch). I don't know if this is enough or there should be more testing? Maybe @franzhaefner has more insights?

**Comment by samuelecalamita** [comment]
@eKrausedivae what about the all page speed with the preview URLs?

**Comment by franzhaefner** [comment]
I am a bit surprised by the result. It should at least be not slower. Why is the loading time more than 2 times than without preloading?
Seems like an outlier.
Did you make sure that you take the values after refreshing the page a few times before taking the values, so all the caches that exists at various locations along the way are properly filled.

I would also like to see a bit more data, than a single value for both cases.

If you are properly sure that this is a consistent behavior, then I am surprised. Maybe the file size of the fonts is so small that there is no benefit to preloading.

**Comment by eKrausedivae** [comment]
Tested with the ContiHome project, preloaded loads faster.
<img width="673" alt="Screenshot 2024-09-24 at 15 33 41" src="https://github.com/user-attachments/assets/035ac2fd-48ff-423f-b07c-e2973b9b5aa1">

Not preloaded:
- Queued at 1.48s
- Started at 1.48s
![image](https://github.com/user-attachments/assets/6149ab1e-1dad-469f-bbf5-8aef30ee9a94)

Preloaded:
- Queued at 412.81ms
- Started at 423.55ms
![image](https://github.com/user-attachments/assets/81db5786-858e-496e-8692-4af113160ef8)

**Comment by franzhaefner** [comment]
That looks good!
That's what I would expect. The download itself takes around the same time, but is started earlier. Thus a better experience for the user (no or at least less font flickering)
